# Generated by Django 4.2.15 on 2024-08-23 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_studentprofile_subscription_end_date_and_more'),
        ('students', '0003_alter_servicesmodel_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsclassificationmodel',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel'),
        ),
        migrations.AddField(
            model_name='productsclassificationmodel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesclassificationmodel',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel'),
        ),
        migrations.AddField(
            model_name='servicesclassificationmodel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
