# Generated by Django 4.2.15 on 2024-08-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_servicesmodel_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='stock',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
