# Generated by Django 4.2.15 on 2024-08-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_productsmodel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='classification',
            field=models.ManyToManyField(blank=True, to='students.productsclassificationmodel'),
        ),
    ]
