# Generated by Django 4.2.15 on 2024-09-03 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0009_serviceorder_student_alter_serviceorder_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceOrder',
            new_name='ServiceOrderModel',
        ),
    ]
