# Generated by Django 4.2.15 on 2025-03-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_salonappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalonAppointment',
        ),
    ]
