# Generated by Django 4.2.15 on 2025-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_delete_salonappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
