# Generated by Django 4.2.15 on 2025-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_servicesmodel_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='age_from',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='age_to',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='subscription_days',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
