# Generated by Django 4.2.15 on 2025-04-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التصنيع'),
        ),
    ]
