# Generated by Django 4.2.15 on 2025-04-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_receptionistprofile_profile_image_base64'),
        ('students', '0018_productsmodel_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='accounts.coachprofile'),
        ),
    ]
