# Generated by Django 4.2.15 on 2025-04-27 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0019_servicesmodel_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecartitem',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='servicecartitem',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicecartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='servicecartitem',
            unique_together={('user', 'service')},
        ),
    ]
