# Generated by Django 4.2.15 on 2025-04-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_rename_added_at_servicecartitem_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecartitem',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.AlterUniqueTogether(
            name='servicecartitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servicecartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='servicecartitem',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='servicecartitem',
            name='updated_at',
        ),
    ]
