# Generated by Django 4.2.15 on 2025-05-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_receptionistprofile_profile_image_base64'),
        ('students', '0021_rename_created_at_servicecartitem_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='coach',
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='services', to='accounts.coachprofile'),
        ),
    ]
