# Generated by Django 4.2.15 on 2025-05-23 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0022_remove_servicesmodel_coach_servicesmodel_coaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('customer_request', 'Customer requested cancellation'), ('payment_failed', 'Payment failed'), ('out_of_stock', 'Product/Service out of stock'), ('duplicate_order', 'Duplicate order'), ('technical_issue', 'Technical issue'), ('fraud_suspected', 'Fraud suspected'), ('other', 'Other')], max_length=50)),
                ('custom_reason', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='students.order')),
            ],
            options={
                'verbose_name': 'Order Cancellation',
                'verbose_name_plural': 'Order Cancellations',
            },
        ),
    ]
