# Generated by Django 4.2.15 on 2025-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_ordercancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transfer_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='transfer_receipts/', verbose_name='إثبات التحويل'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ رفع إثبات التحويل'),
        ),
    ]
