# Generated by Django 4.2.15 on 2025-06-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_order_transfer_receipt_order_transfer_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='pricing_period_months',
            field=models.IntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')], default=1, help_text='Number of months this price covers'),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for the specified pricing period', max_digits=6),
        ),
    ]
