# Generated by Django 4.2.15 on 2025-06-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_coachprofile_vendor_classification'),
        ('students', '0027_alter_productsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='club_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إيرادات النادي'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_vendor_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إجمالي عمولة البائعين'),
        ),
        migrations.CreateModel(
            name='OrderVendorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي مبلغ البائع')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة العمولة (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ العمولة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_commissions', to='students.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coachprofile', verbose_name='البائع')),
            ],
            options={
                'verbose_name': 'عمولة بائع',
                'verbose_name_plural': 'عمولات البائعين',
                'unique_together': {('order', 'vendor')},
            },
        ),
    ]
