# Generated by Django 4.2.15 on 2025-06-19 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0028_order_club_revenue_order_total_vendor_commission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesmodel',
            options={'ordering': ['-creation_date'], 'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='approval_notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات الموافقة/الرفض'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الموافقة'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_services', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة'),
        ),
    ]
