# Generated by Django 4.2.15 on 2025-06-28 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='students.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='students.orderitem'),
            preserve_default=False,
        ),
    ]
