# Generated by Django 4.2.15 on 2025-06-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_remove_review_is_approved_alter_review_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'تم الدفع'), ('delivered', 'تم التسليم'), ('confirmed', 'تم التأكيد'), ('cancelled', 'تم الإلغاء'), ('completed', 'مكتمل')], default='pending', max_length=20),
        ),
    ]
