# Generated by Django 4.2.15 on 2025-07-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_serviceclick_productclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coach_payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid to Coach')], default='pending', max_length=20, verbose_name='Coach Payment Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date to Coach'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Reference'),
        ),
    ]
