# Generated by Django 4.2.15 on 2025-07-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_order_coach_payment_status_order_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coach_payment_status',
        ),
    ]
