# Generated by Django 4.2.15 on 2025-07-21 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0035_customrole'),
        ('students', '0036_order_discount_amount_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_dashboard.subcategory', verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_dashboard.subcategory', verbose_name='التصنيف الفرعي'),
        ),
    ]
