# Generated by Django 4.2.15 on 2025-07-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_productsmodel_subcategory_servicesmodel_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT Percentage'),
        ),
    ]
