# Generated by Django 4.2.15 on 2025-07-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_order_vat_amount_order_vat_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
    ]
