# Generated by Django 4.2.15 on 2025-09-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_remove_order_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='coaches',
        ),
    ]
