# Generated by Django 4.2.15 on 2025-12-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_remove_servicesmodel_coaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Package Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Package Description')),
                ('duration_days', models.IntegerField(default=1, help_text='Duration of package in days')),
                ('sessions_per_week', models.IntegerField(default=1, help_text='Number of sessions per week')),
                ('total_sessions', models.IntegerField(default=1, help_text='Total sessions in package')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted Price')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mark as Popular Package')),
                ('features', models.TextField(blank=True, help_text='List of package features (one per line)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='students.servicesmodel')),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['created_at'],
            },
        ),
    ]
