# Generated by Django 4.2.15 on 2025-12-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_servicepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='pricing_period_months',
        ),
    ]
