# Generated by Django 4.2.15 on 2025-12-04 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0042_remove_servicesmodel_pricing_period_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackageCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('service_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.servicepackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Package Cart Item',
                'verbose_name_plural': 'Service Package Cart Items',
                'unique_together': {('user', 'service_package')},
            },
        ),
    ]
