# Generated by Django 4.2.15 on 2025-12-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_servicepackagecartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='service_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.servicepackage'),
        ),
    ]
