# Generated by Django 4.2.15 on 2025-12-06 19:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_orderitem_service_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal (before VAT)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='VAT Percentage Applied'),
        ),
    ]
