# Generated by Django 4.2.15 on 2025-07-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0065_coachprofile_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable VAT')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='VAT Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vat_settings', to='accounts.clubsmodel')),
            ],
            options={
                'verbose_name': 'VAT Setting',
                'verbose_name_plural': 'VAT Settings',
            },
        ),
    ]
