# Generated by Django 4.2.15 on 2025-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatsettings',
            name='vat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=15.0, max_digits=5, null=True, verbose_name='VAT Percentage'),
        ),
    ]
