# Generated by Django 4.2.15 on 2025-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_dashboard', '0002_alter_vatsettings_vat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatsettings',
            name='currency',
            field=models.CharField(choices=[('ر.س', 'ر.س - Saudi Riyal'), ('$', '$ - US Dollar'), ('€', '€ - Euro'), ('£', '£ - British Pound'), ('د.إ', 'د.إ - UAE Dirham'), ('د.ك', 'د.ك - Kuwaiti Dinar'), ('د.ب', 'د.ب - Bahraini Dinar'), ('ر.ق', 'ر.ق - Qatari Riyal'), ('ر.ع', 'ر.ع - Omani Rial'), ('د.ا', 'د.ا - Algerian Dinar'), ('د.م', 'د.م - Moroccan Dirham'), ('ج.م', 'ج.م - Egyptian Pound'), ('ل.ل', 'ل.ل - Lebanese Pound'), ('ل.س', 'ل.س - Syrian Pound'), ('د.ع', 'د.ع - Iraqi Dinar'), ('ر.ي', 'ر.ي - Yemeni Rial'), ('د.ت', 'د.ت - Tunisian Dinar'), ('د.ل', 'د.ل - Libyan Dinar'), ('ج.س', 'ج.س - Sudanese Pound')], default='ر.س', max_length=10, verbose_name='العملة'),
        ),
    ]
