# Generated by Django 4.2.15 on 2025-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_dashboard', '0003_vatsettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatsettings',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=10, verbose_name='Language'),
        ),
    ]
