# Generated by Django 4.2.15 on 2025-07-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_dashboard', '0004_vatsettings_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vatsettings',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='vatsettings',
            name='vat_percentage',
        ),
    ]
