# Generated by Django 4.2.15 on 2025-07-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_remove_order_tax_amount'),
        ('accounts', '0065_coachprofile_subcategories'),
        ('accountant_dashboard', '0005_remove_vatsettings_is_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Accountant Review'), ('accountant_reviewed', 'Accountant Reviewed'), ('director_reviewed', 'Director Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('accountant_notes', models.TextField(blank=True, null=True)),
                ('director_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_revisions', to='accounts.userprofile')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_revisions', to='accounts.userprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_revisions', to='students.order')),
            ],
            options={
                'verbose_name': 'Bill Revision',
                'verbose_name_plural': 'Bill Revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillRevisionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accountant_dashboard.billrevision')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
