# Generated by Django 4.2.15 on 2025-07-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_coachprofile_subcategories'),
        ('accountant_dashboard', '0006_billrevision_billrevisioncomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('button_text', models.CharField(max_length=50)),
                ('button_url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='accounts.clubsmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
