# Generated by Django 4.2.15 on 2025-07-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_dashboard', '0007_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
    ]
