# Generated by Django 4.2.15 on 2025-07-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_coachprofile_subcategories'),
        ('accountant_dashboard', '0008_remove_banner_button_text_remove_banner_button_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions', to='accounts.clubsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(max_length=200)),
                ('about_title', models.CharField(max_length=200)),
                ('about_description', models.TextField()),
                ('features_title', models.CharField(max_length=200)),
                ('plans_title', models.CharField(max_length=200)),
                ('cta_title', models.CharField(max_length=200)),
                ('cta_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page_content', to='accounts.clubsmodel')),
            ],
        ),
    ]
