# Generated by Django 4.2.15 on 2025-12-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_coachprofile_branches'),
        ('accountant_dashboard', '0009_termsandconditions_landingpagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatsettings',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vat_settingsss', to='accounts.clubsmodel'),
        ),
    ]
