# Generated by Django 4.2.15 on 2025-03-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_coach_profile_userprofile_coach_profile'),
        ('club_dashboard', '0007_clubmodel_updated_at_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.clubsmodel', verbose_name='النادي'),
        ),
        migrations.DeleteModel(
            name='ClubModel',
        ),
    ]
