# Generated by Django 4.2.15 on 2025-03-10 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_coach_profile_userprofile_coach_profile'),
        ('club_dashboard', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_reviews', to='accounts.coachprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to='accounts.studentprofile'),
        ),
    ]
