# Generated by Django 4.2.15 on 2025-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0012_productimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonappointment',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
