# Generated by Django 4.2.15 on 2025-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0014_alter_salonappointment_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
