# Generated by Django 4.2.15 on 2025-04-12 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_clubsmodel_group_chat_enabled_and_more'),
        ('club_dashboard', '0015_productimg_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonappointment',
            name='club',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.clubsmodel', verbose_name='النادي'),
            preserve_default=False,
        ),
    ]
