# Generated by Django 4.2.15 on 2025-04-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_productsmodel_expiration_date_and_more'),
        ('club_dashboard', '0016_salonappointment_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التصنيع')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='students.productsmodel', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'شحنة منتج',
                'verbose_name_plural': 'شحنات المنتجات',
                'ordering': ['expiration_date', 'created_at'],
            },
        ),
    ]
