# Generated by Django 4.2.15 on 2025-05-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0017_productshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonappointment',
            name='day',
            field=models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10),
        ),
    ]
