# Generated by Django 4.2.15 on 2025-05-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0018_alter_salonappointment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonappointment',
            name='day',
            field=models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الإثنين', 'الإثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=10),
        ),
    ]
