# Generated by Django 4.2.15 on 2025-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0019_alter_salonappointment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonappointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
