# Generated by Django 4.2.15 on 2025-05-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0020_salonappointment_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_employee_client_counts', models.BooleanField(default=True, help_text='Toggle visibility of employee and client count cards on student dashboard', verbose_name='Show Employee & Client Counts')),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
    ]
