# Generated by Django 4.2.15 on 2025-05-23 23:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0021_dashboardsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salonappointment',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'موعد الصالون', 'verbose_name_plural': 'مواعيد الصالون'},
        ),
        migrations.RemoveField(
            model_name='salonappointment',
            name='day',
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='التاريخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salonappointment',
            name='available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
        migrations.AlterField(
            model_name='salonappointment',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='وقت النهاية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salonappointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='مدفوع'),
        ),
        migrations.AlterField(
            model_name='salonappointment',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='وقت البداية'),
            preserve_default=False,
        ),
    ]
