# Generated by Django 4.2.15 on 2025-05-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0022_alter_salonappointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salonappointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='salonappointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salonappointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salonappointment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='day',
            field=models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الإثنين', 'الإثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], default='السبت', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salonappointment',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salonappointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salonappointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salonappointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
