# Generated by Django 4.2.15 on 2025-06-17 20:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0046_coachprofile_vendor_classification'),
        ('club_dashboard', '0024_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العمولة')),
                ('commission_type', models.CharField(choices=[('vendor', 'عمولة البائع'), ('time_period', 'عمولة فترة زمنية')], max_length=20, verbose_name='نوع العمولة')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة العمولة (%)')),
                ('vendor_classification', models.CharField(blank=True, choices=[('bronze', 'برونزي'), ('silver', 'فضي'), ('gold', 'ذهبي'), ('platinum', 'بلاتيني')], max_length=20, null=True, verbose_name='تصنيف البائع')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel', verbose_name='النادي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'عمولة',
                'verbose_name_plural': 'العمولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorCommissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التخصيص')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_dashboard.commission', verbose_name='العمولة')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_assignment', to='accounts.coachprofile', verbose_name='البائع')),
            ],
            options={
                'verbose_name': 'تخصيص عمولة البائع',
                'verbose_name_plural': 'تخصيصات عمولة البائعين',
            },
        ),
    ]
