# Generated by Django 4.2.15 on 2025-06-19 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_servicesmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_dashboard', '0026_refunddispute_refunddisputeattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunddispute',
            name='client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='client_refund_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refunddispute',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_disputes', to='students.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='refunddispute',
            name='vendor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_refund_disputes', to=settings.AUTH_USER_MODEL),
        ),
    ]
