# Generated by Django 4.2.15 on 2025-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0027_alter_refunddispute_client_alter_refunddispute_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='vendor_classification',
            field=models.CharField(blank=True, default='silver', max_length=50, null=True, verbose_name='تصنيف البائع'),
        ),
    ]
