# Generated by Django 4.2.15 on 2025-06-20 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0028_alter_commission_vendor_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='مقدار الخصم (%)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('vendor', 'عمولة البائع'), ('time_period', 'عرض لفترة زمنية')], max_length=20, verbose_name='نوع العمولة'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العرض'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العرض'),
        ),
    ]
