# Generated by Django 4.2.15 on 2025-06-20 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0029_commission_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سيتم خصم هذه النسبة من جميع العمولات خلال هذه الفترة', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='مقدار الخصم (%)'),
        ),
    ]
