# Generated by Django 4.2.15 on 2025-06-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0030_alter_commission_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunddispute',
            name='coach_notes',
            field=models.TextField(blank=True, help_text="Coach's notes about the dispute", null=True),
        ),
        migrations.AddField(
            model_name='refunddispute',
            name='is_escalated',
            field=models.BooleanField(default=False, help_text='Whether dispute has been escalated to club admin'),
        ),
        migrations.AlterField(
            model_name='refunddispute',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Coach Review'), ('coach_rejected', 'Rejected by Coach'), ('escalated', 'Escalated to Admin'), ('investigating', 'Under Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
