# Generated by Django 4.2.15 on 2025-06-29 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_remove_review_is_approved_alter_review_order_and_more'),
        ('club_dashboard', '0031_refunddispute_coach_notes_refunddispute_is_escalated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunddispute',
            name='auto_approve_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refunddispute',
            name='auto_escalate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refunddispute',
            name='last_status_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refunddispute',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_disputes', to='students.orderitem'),
        ),
    ]
