# Generated by Django 4.2.15 on 2025-06-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0032_refunddispute_auto_approve_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunddispute',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Vendor Review'), ('coach_rejected', 'Rejected by Vendor'), ('escalated', 'Escalated to Admin'), ('investigating', 'Under Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
