# Generated by Django 4.2.15 on 2025-06-30 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_coachprofile_policies_approved_and_more'),
        ('club_dashboard', '0033_alter_refunddispute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunddispute',
            name='current_stage',
            field=models.CharField(choices=[('student_coach', 'Student-Coach Discussion'), ('receptionist', 'Receptionist Review'), ('director', 'Director Review'), ('resolved', 'Resolved')], default='student_coach', max_length=20),
        ),
        migrations.AddField(
            model_name='refunddispute',
            name='last_message_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refunddispute',
            name='next_escalation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refunddispute',
            name='stage_start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RefundDisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='club_dashboard.refunddispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
