# Generated by Django 4.2.15 on 2025-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0035_customrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[], max_length=20, verbose_name='Commission Type'),
        ),
    ]
