# Generated by Django 4.2.15 on 2025-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0036_alter_commission_commission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrole',
            name='name',
        ),
        migrations.AddField(
            model_name='customrole',
            name='name_ar',
            field=models.CharField(default='dc', max_length=100, verbose_name='Role Name (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customrole',
            name='name_en',
            field=models.CharField(default='d', max_length=100, verbose_name='Role Name (English)'),
            preserve_default=False,
        ),
    ]
