# Generated by Django 4.2.15 on 2025-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0037_remove_customrole_name_customrole_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default='sdc', max_length=100, verbose_name='Arabic Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='dc', max_length=100, verbose_name='English Name'),
            preserve_default=False,
        ),
    ]
