# Generated by Django 4.2.15 on 2025-11-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0038_remove_category_name_category_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ar',
            field=models.CharField(default='dc', max_length=100, verbose_name='Arabic Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(default='dsc', max_length=100, verbose_name='English Name'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name_en', 'name_ar')},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
    ]
