# Generated by Django 4.2.15 on 2025-11-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0039_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('vendor', 'Vendor Commission'), ('time_period', 'Time Period Offer')], max_length=20, verbose_name='Commission Type'),
        ),
    ]
