# Generated by Django 4.2.15 on 2025-12-04 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0040_alter_commission_commission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_en', models.CharField(default='The Premier Platform for', max_length=200)),
                ('hero_title_ar', models.CharField(default='المنصة الرائدة', max_length=200)),
                ('hero_subtitle_en', models.CharField(default='Vendor Excellence', max_length=200)),
                ('hero_subtitle_ar', models.CharField(default='للتميز في التجارة', max_length=200)),
                ('hero_description_en', models.TextField(default='Discover and connect with thousands of vendors to find the perfect products for your needs.')),
                ('hero_description_ar', models.TextField(default='اكتشف وتواصل مع آلاف التجار لتجد المنتجات المثالية لاحتياجاتك.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('about_title_en', models.CharField(default='Why Choose Our Platform', max_length=200)),
                ('about_title_ar', models.CharField(default='لماذا تختار منصتنا', max_length=200)),
                ('about_description_en', models.TextField(default='We provide the tools and connections you need to succeed in your business journey.')),
                ('about_description_ar', models.TextField(default='نحن نقدم الأدوات والروابط التي تحتاجها للنجاح في رحلتك التجارية.')),
                ('features_title_en', models.CharField(default='Platform Features', max_length=200)),
                ('features_title_ar', models.CharField(default='ميزات المنصة', max_length=200)),
                ('cta_title_en', models.CharField(default='Start organizing your business today', max_length=200)),
                ('cta_title_ar', models.CharField(default='ابدأ في تنظيم عملك اليوم', max_length=200)),
                ('cta_description_en', models.TextField(default='Join thousands of vendors using our platform to improve their performance and management')),
                ('cta_description_ar', models.TextField(default='انضم إلى الآلاف من التجار الذين يستخدمون منصتنا لتحسين أدائهم وإدارتهم')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Contents',
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='club_dashboard.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fa-shopping-cart)', max_length=100)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='club_dashboard.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=300)),
                ('question_ar', models.CharField(max_length=300)),
                ('answer_en', models.TextField()),
                ('answer_ar', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='club_dashboard.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='landing/banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='club_dashboard.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
