# Generated by Django 4.2.15 on 2025-12-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0041_landingpagecontent_navitem_landingpagefeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='العنوان (الإنجليزية)')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='العنوان (العربية)')),
                ('working_hours_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='ساعات العمل (الإنجليزية)')),
                ('working_hours_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='ساعات العمل (العربية)')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='تويتر')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='إنستغرام')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لينكدإن')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='يوتيوب')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم واتساب')),
                ('footer_text_en', models.TextField(blank=True, default='All rights reserved', null=True, verbose_name='نص التذييل (الإنجليزية)')),
                ('footer_text_ar', models.TextField(blank=True, default='جميع الحقوق محفوظة', null=True, verbose_name='نص التذييل (العربية)')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='club/footer/', verbose_name='لوجو التذييل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'معلومات الاتصال',
                'verbose_name_plural': 'معلومات الاتصال',
            },
        ),
    ]
