# Generated by Django 4.2.15 on 2025-12-06 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_coachprofile_branches'),
        ('club_dashboard', '0042_clubcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable or disable VAT for this club', verbose_name='Enable VAT')),
                ('percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='VAT percentage to be applied (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='VAT Percentage')),
                ('currency', models.CharField(default='SAR', help_text='Currency code (e.g., SAR, USD, EUR)', max_length=10, verbose_name='Currency')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vat_settings', to='accounts.clubsmodel', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'VAT Settings',
                'verbose_name_plural': 'VAT Settings',
            },
        ),
    ]
