# Generated by Django 4.2.15 on 2025-12-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_coachprofile_branches'),
        ('club_dashboard', '0043_vatsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubcontact',
            options={'verbose_name': 'Club Contact Information', 'verbose_name_plural': 'Club Contact Information'},
        ),
        migrations.AddField(
            model_name='clubcontact',
            name='club',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='accounts.clubsmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='address_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='contact/footer_logos/'),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='footer_text_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='footer_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='working_hours_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='working_hours_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
