# Generated by Django 5.2.9 on 2026-01-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0003_populate_commission_names'),
        ('club_dashboard', '0044_alter_clubcontact_options_clubcontact_club_and_more'),
    ]

    operations = [
    ]
