# Generated by Django 5.2.9 on 2026-01-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0004_make_name_optional'),
        ('club_dashboard', '0045_merge_20260106_2214'),
    ]

    operations = [
    ]
