# Generated by Django 4.2.15 on 2025-12-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0070_coachprofile_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_otp_verification', models.BooleanField(default=True, verbose_name='تفعيل التحقق بخطوتين (OTP)')),
                ('enable_recaptcha', models.BooleanField(default=True, verbose_name='تفعيل reCAPTCHA')),
                ('otp_method', models.CharField(choices=[('whatsapp', 'واتساب'), ('email', 'البريد الإلكتروني'), ('both', 'كليهما')], default='both', max_length=20, verbose_name='طريقة إرسال OTP')),
                ('otp_expiry_minutes', models.PositiveIntegerField(default=5, verbose_name='مدة صلاحية OTP (دقائق)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='accounts.clubsmodel')),
            ],
            options={
                'verbose_name': 'إعدادات الأمان للنادي',
                'verbose_name_plural': 'إعدادات الأمان للأندية',
            },
        ),
    ]
