# Generated by Django 4.2.15 on 2024-08-10 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='اسم الاكادمية')),
                ('city', models.CharField(choices=[('1', 'ابها'), ('2', 'ابو عريش'), ('3', 'احد المسارحة'), ('4', 'الأفلاج'), ('5', 'الاحساء'), ('6', 'الارطاوية'), ('7', 'الباحة'), ('8', 'البكيرية'), ('9', 'الثقبة'), ('10', 'الجبيل'), ('11', 'الخبر'), ('12', 'الخرج'), ('13', 'الخفجي'), ('14', 'الدلم'), ('15', 'الدمام'), ('16', 'الدوادمي'), ('17', 'الرس'), ('18', 'الرقعي'), ('19', 'الرياض'), ('20', 'الزلفي'), ('21', 'السليل'), ('22', 'الطائف'), ('23', 'العلا'), ('24', 'الغاط'), ('25', 'القريات'), ('26', 'القطيف'), ('27', 'القويعية'), ('28', 'المجمعه'), ('29', 'المدينة المنورة'), ('30', 'المذنب'), ('31', 'المزاحمية'), ('32', 'النعيرية'), ('33', 'النماص'), ('34', 'الهفوف'), ('35', 'املج'), ('36', 'بدر'), ('37', 'بريدة'), ('38', 'بقيق'), ('39', 'بلجرشي'), ('40', 'بيشة'), ('41', 'تبوك'), ('42', 'جازان'), ('43', 'جدة'), ('44', 'حائل'), ('45', 'حفر الباطن'), ('46', 'حقل'), ('47', 'حوطة سدير'), ('48', 'خميس مشيط'), ('49', 'خيبر'), ('50', 'دومة الجندل'), ('51', 'رابغ'), ('52', 'رياض الخبراء'), ('53', 'سبت العلايا'), ('54', 'سكاكا'), ('55', 'شرورة'), ('56', 'شقراء'), ('57', 'صبيا'), ('58', 'ضباء'), ('59', 'ضرما'), ('60', 'طريف'), ('61', 'عرعر'), ('62', 'عنيزة'), ('63', 'قرية العليا'), ('64', 'محايل عسير'), ('65', 'مكة المكرمة'), ('66', 'نجران'), ('67', 'وادي الدواسر'), ('68', 'ينبع')], max_length=255, null=True, verbose_name='المدينة')),
                ('district', models.CharField(max_length=250, null=True, verbose_name='الحي')),
                ('street', models.CharField(max_length=250, null=True, verbose_name='الشارع')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clubsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clubsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('has_subscription', models.BooleanField(default=False)),
                ('subscription_start_date', models.DateTimeField()),
                ('subscription_end_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clubsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('1', 'admin'), ('2', 'director'), ('3', 'student'), ('4', 'coach')], max_length=250)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('Coach_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.coachprofile')),
                ('director_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.directorprofile')),
                ('student_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
