# Generated by Django 4.2.15 on 2024-08-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_coach_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
