# Generated by Django 4.2.15 on 2024-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsmodel',
            name='club_profile_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
