# Generated by Django 4.2.15 on 2024-08-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_is_active_userprofile_is_in_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
