# Generated by Django 4.2.15 on 2024-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
