# Generated by Django 4.2.15 on 2025-02-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clubsmodel_about_clubsmodel_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clubsmodel'),
        ),
    ]
