# Generated by Django 4.2.15 on 2025-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_directorprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_base64',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
