# Generated by Django 4.2.15 on 2025-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_profile_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsmodel',
            name='club_profile_image_base64',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
