# Generated by Django 4.2.15 on 2025-03-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_clubsmodel_club_profile_image_base64_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Coach_profile',
            new_name='coach_profile',
        ),
        migrations.AlterField(
            model_name='clubsmodel',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='نبذة'),
        ),
        migrations.AlterField(
            model_name='clubsmodel',
            name='name',
            field=models.CharField(default='Unnamed Club', max_length=250, unique=True, verbose_name='اسم الأكاديمية'),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='نبذة'),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='accounts.clubsmodel'),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='رقم الهاتف'),
        ),
    ]
