# Generated by Django 4.2.15 on 2025-03-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_coach_profile_userprofile_coach_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsmodel',
            name='about',
            field=models.TextField(max_length=255, null=True, verbose_name='نبذة'),
        ),
        migrations.AlterField(
            model_name='clubsmodel',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='اسم الأكاديمية'),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='accounts.clubsmodel'),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
