# Generated by Django 4.2.15 on 2025-03-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_clubsmodel_about_alter_clubsmodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='coach_profile',
            new_name='Coach_profile',
        ),
    ]
