# Generated by Django 4.2.15 on 2025-03-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_coach_profile_userprofile_coach_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Coach_profile',
            new_name='coach_profile',
        ),
    ]
