# Generated by Django 4.2.15 on 2025-03-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_coach_profile_userprofile_coach_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='coach_profile',
            new_name='Coach_profile',
        ),
    ]
