# Generated by Django 4.2.15 on 2025-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userprofile_account_type_receptionistprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='receptionist_profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'director'), ('3', 'student'), ('4', 'coach')], max_length=250),
        ),
        migrations.DeleteModel(
            name='ReceptionistProfile',
        ),
    ]
