# Generated by Django 4.2.15 on 2025-04-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_userprofile_account_type_receptionistprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='stadium',
        ),
    ]
