# Generated by Django 4.2.15 on 2025-04-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_coachprofile_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsmodel',
            name='group_chat_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الدردشة الجماعية'),
        ),
    ]
