# Generated by Django 4.2.15 on 2025-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_clubsmodel_group_chat_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubsmodel',
            name='group_chat_enabled',
        ),
        migrations.AddField(
            model_name='clubsmodel',
            name='chat_enabled',
            field=models.BooleanField(default=True, verbose_name='دردشة مفعلة'),
        ),
    ]
