# Generated by Django 4.2.15 on 2025-04-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_clubsmodel_group_chat_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
