# Generated by Django 4.2.15 on 2025-04-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_studentprofile_profile_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='profile_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
