# Generated by Django 4.2.15 on 2025-04-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_coachprofile_profile_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistprofile',
            name='profile_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
