# Generated by Django 4.2.15 on 2025-05-08 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_receptionistprofile_profile_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'director'), ('3', 'student'), ('4', 'coach'), ('5', 'receptionist'), ('6', 'administrator')], max_length=250),
        ),
        migrations.CreateModel(
            name='AdministrativeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('profile_image_base64', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administartors', to='accounts.clubsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='administrator_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.administrativeprofile'),
        ),
    ]
