# Generated by Django 4.2.15 on 2025-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_userprofile_account_type_administrativeprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('trial', 'تجريبي'), ('active', 'نشط'), ('expiring_soon', 'سينتهي قريبًا'), ('expired', 'منتهي')], default='تجريبي', max_length=20, null=True, verbose_name='حالة الاشتراك اليدوية'),
        ),
    ]
