# Generated by Django 4.2.15 on 2025-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_update_manual_status_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('trial', 'تجريبي'), ('active', 'نشط'), ('expiring_soon', 'سينتهي قريبًا'), ('expired', 'منتهي')], default='trial', max_length=20, null=True, verbose_name='حالة الاشتراك اليدوية'),
        ),
    ]
