# Generated by Django 4.2.15 on 2025-05-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_studentprofile_manual_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprofile',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='accounts.clubsmodel'),
        ),
    ]
