# Generated by Django 4.2.15 on 2025-05-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_administrativeprofile_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsmodel',
            name='articlesDescription',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المقالات'),
        ),
        migrations.AddField(
            model_name='clubsmodel',
            name='productsDescription',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المنتجات'),
        ),
    ]
