# Generated by Django 4.2.15 on 2025-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_clubsmodel_articlesdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsmodel',
            name='pricing',
            field=models.JSONField(default=list),
        ),
    ]
