# Generated by Django 4.2.15 on 2025-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_clubsmodel_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsmodel',
            name='pricing',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
