# Generated by Django 4.2.15 on 2025-05-25 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_clubsmodel_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='stadium',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
