# Generated by Django 4.2.15 on 2025-05-31 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_userprofile_account_type_accountantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accountant_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accountantprofile'),
        ),
    ]
