# Generated by Django 4.2.15 on 2025-05-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_userprofile_accountant_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsmodel',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الحساب'),
        ),
        migrations.AddField(
            model_name='clubsmodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='clubsmodel',
            name='bank_address',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان البنك'),
        ),
        migrations.AddField(
            model_name='clubsmodel',
            name='bank_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بلد البنك'),
        ),
        migrations.AddField(
            model_name='clubsmodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='clubsmodel',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الآيبان'),
        ),
        migrations.AddField(
            model_name='clubsmodel',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود السويفت'),
        ),
    ]
