# Generated by Django 4.2.15 on 2025-06-16 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0042_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachprofile',
            options={'verbose_name': 'بائع', 'verbose_name_plural': 'البائعين'},
        ),
        migrations.RenameField(
            model_name='coachprofile',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='stadium',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='activity_type',
            field=models.CharField(choices=[('football', 'كرة القدم'), ('basketball', 'كرة السلة'), ('volleyball', 'كرة الطائرة'), ('tennis', 'التنس'), ('swimming', 'السباحة'), ('fitness', 'اللياقة البدنية'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='نوع النشاط'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='approval_notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات المدير'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الموافقة'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='business_name',
            field=models.CharField(default='نشاط غير محدد', max_length=200, verbose_name='اسم النشاط التجاري'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='city',
            field=models.CharField(default='غير محددة', max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='وصف الخدمة'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='district',
            field=models.CharField(default='غير محددة', max_length=100, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='street',
            field=models.CharField(default='غير محددة', max_length=200, verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel', verbose_name='النادي'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='full_name',
            field=models.CharField(default='بائع جديد', max_length=100, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='profile_image_base64',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Coach_profile',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.coachprofile'),
        ),
    ]
