# Generated by Django 4.2.15 on 2025-06-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_userprofile_coach_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='business_document_file',
            field=models.TextField(blank=True, help_text='Base64 encoded file (PDF or Image)', null=True, verbose_name='ملف الوثيقة التجارية'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='business_document_type',
            field=models.CharField(blank=True, choices=[('', 'اختر نوع الوثيقة'), ('freelance', 'وثيقة العمل الحر'), ('commercial_register', 'صورة السجل التجاري')], default='', max_length=50, verbose_name='نوع وثيقة النشاط التجاري'),
        ),
    ]
