# Generated by Django 4.2.15 on 2025-06-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_coachprofile_business_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='vendor_classification',
            field=models.CharField(choices=[('bronze', 'برونزي'), ('silver', 'فضي'), ('gold', 'ذهبي'), ('platinum', 'بلاتيني')], default='silver', max_length=20, verbose_name='تصنيف البائع'),
        ),
    ]
