# Generated by Django 4.2.15 on 2025-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_coachprofile_vendor_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='vendor_classification',
            field=models.CharField(default='silver', max_length=50, verbose_name='تصنيف البائع'),
        ),
    ]
