# Generated by Django 4.2.15 on 2025-06-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_coachprofile_vendor_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='policies_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='policy_documents',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
