# Generated by Django 4.2.15 on 2025-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_coachprofile_policies_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistprofile',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='last_assignment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('busy', 'Busy'), ('hold', 'On Hold')], default='free', max_length=10),
        ),
    ]
