# Generated by Django 4.2.15 on 2025-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_receptionistprofile_hold_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='has_subscription',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='manual_status',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='subscription_start_date',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
