# Generated by Django 4.2.15 on 2025-07-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_studentprofile_has_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='business_name',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='business_name_ar',
            field=models.CharField(default='نشاط غير محدد', max_length=200, verbose_name='اسم النشاط التجاري (عربي)'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='business_name_en',
            field=models.CharField(default='Unspecified Business', max_length=200, verbose_name='Business Name (English)'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='number_of_branches',
            field=models.PositiveIntegerField(default=1, help_text='عدد الفروع', verbose_name='Number of Branches'),
        ),
    ]
