# Generated by Django 4.2.15 on 2025-07-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_remove_coachprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الحساب'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الآيبان'),
        ),
    ]
