# Generated by Django 4.2.15 on 2025-07-02 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_coachprofile_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='commercial_registration_certificate',
            field=models.TextField(blank=True, help_text='Base64 encoded file (PDF or Image)', null=True, verbose_name='شهادة السجل التجاري'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='commercial_registration_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='رقم السجل التجاري يجب أن يكون 10 أرقام بالضبط', regex='^\\d{10}$')], verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='store_logo_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image file', null=True, verbose_name='شعار المتجر'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='tax_certificate',
            field=models.TextField(blank=True, help_text='Base64 encoded file (PDF or Image)', null=True, verbose_name='شهادة الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='tax_number',
            field=models.CharField(blank=True, help_text='اختياري - 15 رقم', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='الرقم الضريبي يجب أن يكون 15 رقم بالضبط', regex='^\\d{15}$')], verbose_name='الرقم الضريبي'),
        ),
    ]
