# Generated by Django 4.2.15 on 2025-07-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_coachprofile_commercial_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='is_working_hours_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل ساعات العمل'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='special_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='ساعات العمل الخاصة'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='ساعات العمل'),
        ),
    ]
