# Generated by Django 4.2.15 on 2025-07-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0035_customrole'),
        ('accounts', '0054_coachprofile_is_working_hours_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_dashboard.customrole'),
        ),
    ]
