# Generated by Django 4.2.15 on 2025-07-06 19:26

from django.db import migrations


def migrate_activity_types(apps, schema_editor):
    CoachProfile = apps.get_model('accounts', 'CoachProfile')
    Category = apps.get_model('club_dashboard', 'Category')  # Adjust if your Category is in a different app

    # Create categories if they don't exist
    activity_mapping = {
        'football': 'كرة القدم',
        'basketball': 'كرة السلة',
        'volleyball': 'كرة الطائرة',
        'tennis': 'التنس',
        'swimming': 'السباحة',
        'fitness': 'اللياقة البدنية',
        'other': 'أخرى',
    }

    for slug, name in activity_mapping.items():
        Category.objects.get_or_create(
            name=name,
            slug=slug,
            defaults={'is_active': True}
        )

    # Update coach profiles
    for coach in CoachProfile.objects.all():
        if coach.activity_type:  # Only if it had a value
            category = Category.objects.get(slug=coach.activity_type)
            coach.activity_type_new = category  # Assuming you add a temp field first
            coach.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_otp_options_otp_delivery_method_otp_is_used_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_activity_types),
    ]
