# Generated by Django 4.2.15 on 2025-07-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_migrate_activity_types'),
    ]

    operations = [
        # Add the new ForeignKey field (don't remove the old one yet)
        migrations.AddField(
            model_name='coachprofile',
            name='activity_type_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='club_dashboard.category',  # Adjust if Category is in a different app
                verbose_name='نوع النشاط'
            ),
        ),
    ]
