# Generated by Django 4.2.15 on 2025-07-06 19:48

from django.db import migrations


def migrate_activity_types_forward(apps, schema_editor):
    """Convert old CharField choices to ForeignKey references"""
    CoachProfile = apps.get_model('accounts', 'CoachProfile')
    Category = apps.get_model('club_dashboard', 'Category')  # Adjust app name if needed

    # Create categories if they don't exist
    activity_mapping = {
        'football': 'كرة القدم',
        'basketball': 'كرة السلة',
        'volleyball': 'كرة الطائرة',
        'tennis': 'التنس',
        'swimming': 'السباحة',
        'fitness': 'اللياقة البدنية',
        'other': 'أخرى',
    }

    # Create categories
    for slug, name in activity_mapping.items():
        category, created = Category.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'is_active': True,
                'description': f'فئة {name}'
            }
        )
        print(f"Category {name}: {'created' if created else 'exists'}")

    # Update coach profiles
    updated_count = 0
    for coach in CoachProfile.objects.all():
        if hasattr(coach, 'activity_type') and coach.activity_type:
            try:
                # Find the corresponding category
                category = Category.objects.get(slug=coach.activity_type)
                coach.activity_type_new = category
                coach.save()
                updated_count += 1
                print(f"Updated coach {coach.id}: {coach.activity_type} -> {category.name}")
            except Category.DoesNotExist:
                print(f"Warning: No category found for activity_type '{coach.activity_type}' on coach {coach.id}")

    print(f"Successfully updated {updated_count} coach profiles")


def migrate_activity_types_reverse(apps, schema_editor):
    """Reverse migration: convert ForeignKey back to CharField"""
    CoachProfile = apps.get_model('accounts', 'CoachProfile')

    for coach in CoachProfile.objects.all():
        if coach.activity_type_new:
            coach.activity_type = coach.activity_type_new.slug
            coach.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_add_activity_type_fk'),
    ]

    operations = [
        migrations.RunPython(
            migrate_activity_types_forward,
            migrate_activity_types_reverse
        ),
    ]
