# Generated by Django 4.2.15 on 2025-07-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_migrate_activity_type_data'),
    ]

    operations = [
        # Remove the old CharField
        migrations.RemoveField(
            model_name='coachprofile',
            name='activity_type',
        ),
        # Rename the new field to the original name
        migrations.RenameField(
            model_name='coachprofile',
            old_name='activity_type_new',
            new_name='activity_type',
        ),
    ]
