# Generated by Django 4.2.15 on 2025-07-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_finalize_activity_type_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='region',
            field=models.CharField(choices=[('الرياض', 'الرياض'), ('مكة المكرمة', 'مكة المكرمة'), ('القصيم', 'القصيم'), ('المنطقة الشرقية', 'المنطقة الشرقية'), ('عسير', 'عسير'), ('تيرك', 'تيرك'), ('حائل', 'حائل'), ('الحدود الشمالية', 'الحدود الشمالية'), ('جازان', 'جازان'), ('نجران', 'نجران'), ('الباحة', 'الباحة'), ('الجوف', 'الجوف'), ('المدينة المنورة', 'المدينة المنورة')], default='غير محددة', max_length=50, verbose_name='المنطقة'),
        ),
    ]
