# Generated by Django 4.2.15 on 2025-07-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_coachprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'director'), ('3', 'student'), ('4', 'coach'), ('5', 'receptionist'), ('6', 'administrator'), ('7', 'accountant'), ('8', 'vendor_manager')], max_length=250),
        ),
        migrations.CreateModel(
            name='VendorManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(blank=True, null=True)),
                ('region', models.CharField(choices=[('الرياض', 'الرياض'), ('مكة المكرمة', 'مكة المكرمة'), ('القصيم', 'القصيم'), ('المنطقة الشرقية', 'المنطقة الشرقية'), ('عسير', 'عسير'), ('تبوك', 'تبوك'), ('حائل', 'حائل'), ('الحدود الشمالية', 'الحدود الشمالية'), ('جازان', 'جازان'), ('نجران', 'نجران'), ('الباحة', 'الباحة'), ('الجوف', 'الجوف'), ('المدينة المنورة', 'المدينة المنورة')], max_length=50, verbose_name='المنطقة المسؤولة')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel')),
            ],
            options={
                'verbose_name': 'مدير التجار',
                'verbose_name_plural': 'مديري التجار',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_manager_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendormanagerprofile'),
        ),
    ]
