# Generated by Django 4.2.15 on 2025-07-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_alter_userprofile_account_type_vendormanagerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'director'), ('3', 'student'), ('4', 'coach'), ('5', 'receptionist'), ('6', 'administrator'), ('7', 'accountant'), ('8', 'vendor_manager'), ('9', 'custom_profile')], max_length=250),
        ),
        migrations.CreateModel(
            name='CustomRoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('profile_image_base64', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel')),
            ],
            options={
                'verbose_name': 'Custom Role Profile',
                'verbose_name_plural': 'Custom Role Profiles',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_role_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customroleprofile'),
        ),
    ]
