# Generated by Django 4.2.15 on 2025-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_userprofile_account_type_customroleprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='business_phone_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of business contact numbers in JSON format', verbose_name='أرقام التواصل التجارية'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='business_photo_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image file for the business', null=True, verbose_name='صورة النشاط التجاري'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='whatsapp_business_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب التجاري'),
        ),
    ]
