# Generated by Django 4.2.15 on 2025-07-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_dashboard', '0035_customrole'),
        ('accounts', '0064_coachprofile_business_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='التخصصات الفرعية التي يعمل بها البائع', to='club_dashboard.subcategory', verbose_name='التخصصات الفرعية'),
        ),
    ]
