# Generated by Django 4.2.15 on 2025-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_coachprofile_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsmodel',
            name='promotion_base_price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Base price per day for promotions', max_digits=10),
        ),
    ]
