# Generated by Django 4.2.15 on 2025-09-13 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='business_name_ar',
            field=models.CharField(max_length=200, verbose_name='اسم النشاط التجاري (عربي)'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='business_name_en',
            field=models.CharField(max_length=200, verbose_name='Business Name (English)'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='اسم المدينة يمكن أن يحتوي فقط على أحرف عربية وإنجليزية / City name can only contain Arabic and English letters', regex='^[\\u0600-\\u06FFa-zA-Z\\s\\-]+$')], verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator(message='الوصف يمكن أن يحتوي فقط على أحرف عربية وإنجليزية وأرقام ورموز محددة / Description can only contain Arabic, English letters, numbers, and specific symbols', regex='^[\\u0600-\\u06FFa-zA-Z0-9\\s\\.\\,\\!\\?\\-\\_\\(\\)\\:\\;\\\'\\"\\@\\#\\$\\%\\&\\*\\+\\=\\[\\]\\{\\}\\\\\\/\\<\\>]+$')], verbose_name='وصف الخدمة'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='district',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='اسم الحي يمكن أن يحتوي فقط على أحرف عربية وإنجليزية / District name can only contain Arabic and English letters', regex='^[\\u0600-\\u06FFa-zA-Z\\s\\-]+$')], verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='الاسم الكامل يمكن أن يحتوي فقط على أحرف عربية وإنجليزية / Full name can only contain Arabic and English letters', regex='^[\\u0600-\\u06FFa-zA-Z\\s]+$')], verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='street',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='اسم الشارع يمكن أن يحتوي فقط على أحرف عربية وإنجليزية وأرقام / Street name can only contain Arabic, English letters, and numbers', regex='^[\\u0600-\\u06FFa-zA-Z0-9\\s\\-\\.\\,]+$')], verbose_name='الشارع'),
        ),
    ]
