# Generated by Django 4.2.15 on 2025-11-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_coachprofile_business_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='branches',
            field=models.JSONField(blank=True, default=list, help_text='معلومات عن فروع النشاط التجاري', verbose_name='فروع النشاط التجاري'),
        ),
    ]
