# Generated by Django 5.2.9 on 2026-01-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_coachprofile_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='main_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='main_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
