# Generated by Django 4.2.15 on 2024-08-23 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clubsmodel_club_profile_image_base64_and_more'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='messenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel'),
        ),
    ]
