# Generated by Django 4.2.15 on 2024-08-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_is_active_userprofile_is_in_chat_and_more'),
        ('messenger', '0002_alter_messagesmodel_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockusermodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_creator', to='accounts.clubsmodel'),
        ),
        migrations.AlterField(
            model_name='favoriteusermodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_creator', to='accounts.clubsmodel'),
        ),
    ]
