# Generated by Django 4.2.15 on 2025-04-12 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_messengermodel_is_group_chat_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='messenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.messengermodel'),
        ),
    ]
