# Generated by Django 4.2.15 on 2025-04-12 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_clubsmodel_group_chat_enabled'),
        ('messenger', '0005_alter_messagesmodel_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='messenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel'),
        ),
    ]
