# Generated by Django 4.2.15 on 2025-04-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_alter_messagesmodel_messenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengermodel',
            name='is_group_chat_enabled',
        ),
    ]
