# Generated by Django 4.2.15 on 2025-04-12 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_clubsmodel_group_chat_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0007_remove_messengermodel_is_group_chat_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagesmodel',
            name='messenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clubsmodel'),
        ),
        migrations.AlterField(
            model_name='messagesmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
