# Generated by Django 4.2.15 on 2025-04-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_messagesmodel_receiver_alter_messagesmodel_messenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='messenger_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.messengermodel'),
        ),
    ]
