"""
Django settings for sportclub project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6b1mw+^bk3)_5hys8=%1b-#8j+d*70q9t=px4-6ouary0ymve3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['warehouse2-production.up.railway.app', '127.0.0.1', 'localhost', '*']

CSRF_TRUSTED_ORIGINS = [
    'https://warehouse2-production.up.railway.app',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Application definition

INSTALLED_APPS = [
    'daphne',
    'messenger',
    'students',
    'coach_dashboard',
    'accounts',
    'admin_dashboard',
    'club_dashboard',
    'accountant_dashboard',
    'pages',
    'receptionist_dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'modeltranslation',
    'ckeditor',
    'ckeditor_uploader',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'coach_dashboard.middleware.CoachPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'club_dashboard.vendor_manager_middleware.VendorManagerMiddleware',
]


USE_L10N = True

LANGUAGE_CODE = 'ar'

ROOT_URLCONF = 'sportclub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.club_context',
                'students.context_processors.cart_items_count',
                'club_dashboard.context_processors.club_notifications',
                'club_dashboard.context_processors.club_contact_info',
                'pages.context_processors.language_context',
                'receptionist_dashboard.context_processors.ticket_notifications',
                'students.context_processors.cart_context',
            ],
        },
    },
]

ASGI_APPLICATION = "sportclub.asgi.application"
# WSGI_APPLICATION = 'sportclub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import os
import dj_database_url

# Read environment variables
SECRET_KEY = os.environ.get('SECRET_KEY', 'optional-default-for-local-dev')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Database configuration
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )
}


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'sportclub/static']

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email settings (SMTP Configuration)
# Replace with actual email details
# ============================================================================
# EMAIL SETTINGS (SMTP Configuration) - FIXED VERSION
# ============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'af5275794@gmail.com'
EMAIL_HOST_PASSWORD = 'tnxm zlrz lrny rzcq'  # Gmail App Password
DEFAULT_FROM_EMAIL = 'af5275794@gmail.com'  # Use your actual email
EMAIL_TIMEOUT = 10  # CRITICAL: Timeout after 10 seconds to prevent worker hangs
# ============================================================================
LOGIN_URL = 'http://127.0.0.1:8000/auth/signin/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# في settings.py
NEOLEAP_CONFIG = {
    'CLIENT_ID': '1278490599',
    'USERNAME': 'a61bacbc-3096-4e30-968c-f5124aa2a465',
    'PASSWORD': 'ps6mURldytqeAuqgD3bbF7ORWL6MPkrA',
    'TARGET_MERCHANT_ID': '1278490599',  # احصل على القيمة الصحيحة
    'TARGET_WALLET_NUMBER': '99001',      # احصل على القيمة الصحيحة
    'TARGET_TERMINAL_ID': '2446',         # احصل على القيمة الصحيحة
    'BASE_URL': 'https://walletsit.neoleap.com.sa/merchantb2b'
}

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ]
    },
    'article_editor': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
            ['TextColor', 'BGColor'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['RemoveFormat', 'Source', 'Preview']
        ],
        'height': 400,
        'width': '100%',
        'filebrowserWindowWidth': 940,
        'filebrowserWindowHeight': 725,
    }
}


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MAIN_CLUB_ID = 4
MAIN_CLUB_DIRECTOR_EMAIL = "naghammohamed287@gmail.com"

# WhatsApp Configuration
WHATSAPP_SENDER_NUMBER = '+201090871358'
WHATSAPP_ENABLED = True

# OTP Configuration
OTP_EXPIRY_MINUTES = 5
OTP_RESEND_COOLDOWN_SECONDS = 60


RECAPTCHA_PUBLIC_KEY = '6LfwLZIrAAAAANqXLMPf8G903mXu1KihzlCuC6SK'
RECAPTCHA_PRIVATE_KEY = '6LfwLZIrAAAAAFQsd1CIklEZHSGrZu22gkp6T2q0'