# Generated by Django 4.2.15 on 2024-08-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_subscription_end_date_and_more'),
        ('coach_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAppointmentPresence',
            new_name='StudentAppointmentPresenceModel',
        ),
    ]
