# Generated by Django 4.2.15 on 2024-09-02 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_productsmodel_classification'),
        ('coach_dashboard', '0002_rename_studentappointmentpresence_studentappointmentpresencemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachappointmentsmodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.servicesmodel'),
        ),
    ]
