# Generated by Django 4.2.15 on 2025-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_dashboard', '0003_coachappointmentsmodel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الإثنين', 'الإثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=10)),
                ('time', models.TimeField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
