# Generated by Django 4.2.15 on 2025-05-25 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach_dashboard', '0005_delete_salonappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('appointment_day', models.CharField(max_length=20)),
                ('appointment_start_time', models.TimeField()),
                ('appointment_end_time', models.TimeField()),
                ('coach_name', models.CharField(max_length=200)),
                ('is_present', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('booking_id', 'appointment_day', 'appointment_start_time', 'student')},
            },
        ),
    ]
