# Generated by Django 4.2.15 on 2025-05-25 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach_dashboard', '0006_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['appointment_day', 'appointment_start_time', 'student__username'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When record was first created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='appointment_day',
            field=models.CharField(help_text='Day of the appointment', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='appointment_end_time',
            field=models.TimeField(help_text='End time of the appointment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='appointment_start_time',
            field=models.TimeField(help_text='Start time of the appointment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='booking_id',
            field=models.IntegerField(help_text='ID of the booking/appointment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='coach_name',
            field=models.CharField(help_text='Name of the coach', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_recorded',
            field=models.DateTimeField(auto_now=True, help_text='When attendance was recorded'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False, help_text='Is the student present?'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(help_text='Student user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
