# Generated by Django 4.2.15 on 2025-06-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_dashboard', '0007_alter_attendance_options_attendance_date_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
