# Generated by Django 4.2.15 on 2025-06-15 21:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach_dashboard', '0008_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('booking_id', 'appointment_day', 'appointment_start_time', 'student')},
        ),
    ]
