# Generated by Django 4.2.15 on 2025-06-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_dashboard', '0009_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachappointmentsmodel',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='coachappointmentsmodel',
            name='service',
        ),
        migrations.RemoveField(
            model_name='studentappointmentpresencemodel',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='studentappointmentpresencemodel',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='CoachAppointmentsModel',
        ),
        migrations.DeleteModel(
            name='StudentAppointmentPresenceModel',
        ),
    ]
