# Generated by Django 4.2.15 on 2025-06-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_coachprofile_policies_approved_and_more'),
        ('coach_dashboard', '0012_coachreceptionistticket_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachreceptionistticket',
            name='receptionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to='accounts.receptionistprofile'),
        ),
    ]
