# Generated by Django 4.2.15 on 2025-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_dashboard', '0013_alter_coachreceptionistticket_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('refund', 'Refund Request'), ('review', 'New Review'), ('ticket', 'Support Ticket'), ('other', 'Other')], default='other', max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
