# Generated by Django 4.2.15 on 2025-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_dashboard', '0014_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachreceptionistticket',
            name='assignment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachreceptionistticket',
            name='resolution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachreceptionistticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
