# Generated by Django 4.2.15 on 2025-07-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_remove_order_coach_payment_status'),
        ('accounts', '0063_alter_userprofile_account_type_customroleprofile_and_more'),
        ('coach_dashboard', '0015_coachreceptionistticket_assignment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=20)),
                ('promotion_level', models.CharField(choices=[('standard', 'Standard (Free)'), ('featured', 'Featured (Paid)'), ('premium', 'Premium (Paid)')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.coachprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.productsmodel')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.servicesmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
