# Generated by Django 4.2.15 on 2025-07-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_coachprofile_business_phone_numbers_and_more'),
        ('coach_dashboard', '0016_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('standard', 'Standard (Free)'), ('featured', 'Featured (Paid)'), ('premium', 'Premium (Paid)')], max_length=20, verbose_name='مستوى الترويج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_days', models.PositiveIntegerField(verbose_name='المدة بالأيام')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_prices', to='accounts.clubsmodel', verbose_name='النادي')),
            ],
            options={
                'verbose_name': 'سعر الترويج',
                'verbose_name_plural': 'أسعار الترويج',
                'unique_together': {('club', 'level')},
            },
        ),
    ]
