# Generated by Django 4.2.15 on 2025-07-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_dashboard', '0017_promotionprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionprice',
            name='duration_days',
        ),
    ]
