# Generated by Django 4.2.15 on 2025-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_dashboard', '0018_remove_promotionprice_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionprice',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='المدة بالأيام'),
            preserve_default=False,
        ),
    ]
