# Generated by Django 4.2.15 on 2025-07-12 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_coachprofile_business_phone_numbers_and_more'),
        ('coach_dashboard', '0020_coupon_couponusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='coach_dashboard.coupon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Coupon Activation',
                'verbose_name_plural': 'Coupon Activations',
                'unique_together': {('coupon', 'student')},
            },
        ),
    ]
