# Generated by Django 4.2.15 on 2025-08-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_coachprofile_subcategories'),
        ('coach_dashboard', '0021_couponactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Schedule Title')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('monday_open', models.TimeField(blank=True, null=True, verbose_name='Monday Open')),
                ('monday_close', models.TimeField(blank=True, null=True, verbose_name='Monday Close')),
                ('tuesday_open', models.TimeField(blank=True, null=True, verbose_name='Tuesday Open')),
                ('tuesday_close', models.TimeField(blank=True, null=True, verbose_name='Tuesday Close')),
                ('wednesday_open', models.TimeField(blank=True, null=True, verbose_name='Wednesday Open')),
                ('wednesday_close', models.TimeField(blank=True, null=True, verbose_name='Wednesday Close')),
                ('thursday_open', models.TimeField(blank=True, null=True, verbose_name='Thursday Open')),
                ('thursday_close', models.TimeField(blank=True, null=True, verbose_name='Thursday Close')),
                ('friday_open', models.TimeField(blank=True, null=True, verbose_name='Friday Open')),
                ('friday_close', models.TimeField(blank=True, null=True, verbose_name='Friday Close')),
                ('saturday_open', models.TimeField(blank=True, null=True, verbose_name='Saturday Open')),
                ('saturday_close', models.TimeField(blank=True, null=True, verbose_name='Saturday Close')),
                ('sunday_open', models.TimeField(blank=True, null=True, verbose_name='Sunday Open')),
                ('sunday_close', models.TimeField(blank=True, null=True, verbose_name='Sunday Close')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_working_hours', to='accounts.coachprofile')),
            ],
            options={
                'verbose_name': 'Vendor Working Hours',
                'verbose_name_plural': 'Vendor Working Hours',
                'ordering': ['-is_active', '-start_date'],
            },
        ),
    ]
