# Generated by Django 4.2.15 on 2025-08-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_coachprofile_subcategories'),
        ('coach_dashboard', '0022_vendorworkinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Package Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price')),
                ('search_priority_level', models.PositiveIntegerField(default=0, verbose_name='Search Priority Level')),
                ('homepage_placement', models.BooleanField(default=False, verbose_name='Homepage Placement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion Package',
                'verbose_name_plural': 'Promotion Packages',
            },
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='promotion_level',
        ),
        migrations.AddField(
            model_name='promotion',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration in Days'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Paid'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('product', 'منتج'), ('service', 'خدمة')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('pending', 'في انتظار الموافقة'), ('rejected', 'مرفوض'), ('expired', 'منتهي الصلاحية')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='promotionprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach_dashboard.promotionpackage', verbose_name='Promotion Package'),
        ),
        migrations.AddField(
            model_name='promotionprice',
            name='promotion_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach_dashboard.promotionpackage', verbose_name='Promotion Package'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='promotionprice',
            unique_together={('club', 'promotion_package', 'duration_days')},
        ),
        migrations.RemoveField(
            model_name='promotionprice',
            name='level',
        ),
    ]
