# Generated by Django 4.2.15 on 2025-08-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_coachprofile_subcategories'),
        ('coach_dashboard', '0023_promotionpackage_remove_promotion_promotion_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for base price (e.g., 1.5 = 50% increase)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_features', to='accounts.clubsmodel')),
            ],
            options={
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='promotionprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promotionprice',
            name='club',
        ),
        migrations.RemoveField(
            model_name='promotionprice',
            name='promotion_package',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='price_paid',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='promotion_package',
        ),
        migrations.AddField(
            model_name='promotion',
            name='base_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='PromotionPackage',
        ),
        migrations.DeleteModel(
            name='PromotionPrice',
        ),
        migrations.AddField(
            model_name='promotion',
            name='features',
            field=models.ManyToManyField(blank=True, to='coach_dashboard.promotionfeature'),
        ),
    ]
