# Generated by Django 4.2.15 on 2025-04-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_servicesmodel_age_from_and_more'),
        ('accounts', '0023_remove_coachprofile_stadium'),
        ('receptionist_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonbooking',
            name='service_type',
        ),
        migrations.AddField(
            model_name='salonbooking',
            name='service',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='students.servicesmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coachprofile'),
        ),
    ]
