# Generated by Django 4.2.15 on 2025-04-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_servicesmodel_age_from_and_more'),
        ('receptionist_dashboard', '0002_remove_salonbooking_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonbooking',
            name='employee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.servicesmodel'),
        ),
    ]
