# Generated by Django 4.2.15 on 2025-04-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_servicesmodel_age_from_and_more'),
        ('receptionist_dashboard', '0003_alter_salonbooking_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonbooking',
            name='service_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.servicesmodel'),
        ),
    ]
