# Generated by Django 4.2.15 on 2025-04-07 18:03

from django.db import migrations

def fix_booking_data(apps, schema_editor):
    # Get the SalonBooking model
    SalonBooking = apps.get_model('receptionist_dashboard', 'SalonBooking')

    # Fix the problematic record with ID 3
    try:
        booking = SalonBooking.objects.get(pk=3)
        # You might want to delete it if you don't need this booking
        booking.delete()
        # Or fix it with a valid employee value if you want to keep it
        # booking.employee = "Valid Employee Name"
        # booking.save()
    except SalonBooking.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_dashboard', '0004_salonbooking_service_type_alter_salonbooking_service'),
    ]

    operations = [
        migrations.RunPython(fix_booking_data),
    ]
