# Generated by Django 4.2.15 on 2025-04-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_servicesmodel_age_from_and_more'),
        ('accounts', '0023_remove_coachprofile_stadium'),
        ('receptionist_dashboard', '0005_auto_20250407_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salonbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='salonbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='employee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='students.servicesmodel'),
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='service_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_bookings', to='accounts.studentprofile'),
        ),
    ]
