# Generated by Django 4.2.15 on 2025-04-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_servicesmodel_age_from_and_more'),
        ('receptionist_dashboard', '0006_alter_salonbooking_options_salonbooking_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonbooking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='salonbooking',
            name='service_type',
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='receptionist_dashboard.salonbooking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='students.servicesmodel')),
            ],
            options={
                'unique_together': {('booking', 'service')},
            },
        ),
    ]
