# Generated by Django 4.2.15 on 2025-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_dashboard', '0007_remove_salonbooking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='coach_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
