# Generated by Django 4.2.15 on 2025-05-09 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_dashboard', '0008_bookingservice_coach_id_bookingservice_coach_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonbooking',
            name='student',
        ),
    ]
