# Generated by Django 4.2.15 on 2025-06-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_passwordresettoken'),
        ('receptionist_dashboard', '0010_salonbooking_created_by_salonbooking_created_by_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingservice',
            name='coach_id',
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='accounts.coachprofile'),
        ),
        migrations.AddField(
            model_name='salonbooking',
            name='primary_coach',
            field=models.ForeignKey(blank=True, help_text='Primary coach for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_bookings', to='accounts.coachprofile'),
        ),
    ]
